#-
#    label:  "Главная"
#    action: "index:index"
#    position: "first"
#    icon: "icon-home"
-
    label:  "Настройки"
    name: "settings"
    action: "settings:index"
    position: "last"
    icon: "icon-cog"
-
    label:  "Информация"
    parent: "settings"
    action: "tools:info"
