-
    label:  "Главная"
    action: "index:index"
    position: "first"
    icon: "icon-home"
-
    label:  "Настройки"
    name: "settings"
    action: "settings:index"
    position: "last"
    icon: "icon-wrench"
-
    label:  "Информация PHP"
    parent: "settings"
    action: "tools:phpinfo"
