-
    label:  "Настройки"
    name: "settings"
    action: "settings:index"
    position: "last"
    icon: "icon-cog"
-
    label:  "Информация"
    parent: "settings"
    action: "tools:info"
-
    label:  "Бандлы"
    parent: "settings"
    action: "bundles:index"
    env: "dev"
