parameters:
    ns_admin.service.class:                  'NS\AdminBundle\Service\AdminService'
    ns_admin.menu.resolver.collection.class: 'NS\AdminBundle\Menu\Resolver\MenuResolverCollection'
    ns_admin.menu.resolver.bundles.class:    'NS\AdminBundle\Menu\Resolver\BundlesMenuResolver'
    ns_admin.menu.resolver.settings.class:   'NS\AdminBundle\Menu\Resolver\SettingsMenuResolver'

services:
    ns_admin.menu.resolver.collection:
        class: %ns_admin.menu.resolver.collection.class%

    ns_admin.menu.resolver.bundles:
        class: %ns_admin.menu.resolver.bundles.class%
        arguments: [@ns_admin.service, @knp_menu.factory]
        tags:
            - { name: ns_admin.menu.resolver }

    ns_admin.menu.resolver.settings:
        class: %ns_admin.menu.resolver.settings.class%
        arguments: [@ns_admin.service, @knp_menu.factory]
        tags:
            - { name: ns_admin.menu.resolver }

    ns_admin.menu_builder:
        class: NS\AdminBundle\Menu\Builder
        arguments: [@knp_menu.factory, @ns_admin.service, @knp_menu.matcher, @ns_admin.menu.resolver.collection]

    ns_admin.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: ns_admin.menu_builder
        factory_method: createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }

    ns_admin.service:
        class: %ns_admin.service.class%
        arguments: [%ns_admin.bundles%, @kernel]
