parameters:
    ns_admin.service.class: 'NS\AdminBundle\Service\AdminService'

services:
    ns_admin.menu_builder:
        class: NS\AdminBundle\Menu\Builder
        arguments: [@knp_menu.factory, @ns_admin.service, @knp_menu.matcher]

    ns_admin.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: ns_admin.menu_builder
        factory_method: createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }

    ns_admin.service:
        class: %ns_admin.service.class%
        arguments: [%ns_admin.bundles%, @kernel]
